create table "public"."club" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "description" text,
    "is_private" boolean not null,
    "max_participants" numeric not null,
    "owner_id" bigint not null,
    "invite_link" text
);


alter table "public"."club" enable row level security;

create table "public"."club_membership" (
    "id" bigint generated by default as identity not null,
    "joined_at" timestamp with time zone not null default now(),
    "user_id" bigint not null,
    "club_id" bigint not null
);


alter table "public"."club_membership" enable row level security;

create table "public"."gauntlet" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "description" text,
    "status" text,
    "club_id" bigint,
    "session_count" numeric,
    "current_session" numeric,
    "max_votes" numeric,
    "min_votes" numeric,
    "points_per_session" numeric
);


alter table "public"."gauntlet" enable row level security;

create table "public"."profile" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "username" text not null,
    "email" text not null
);


alter table "public"."profile" enable row level security;

create table "public"."session" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "gauntlet_id" bigint not null,
    "theme" text not null,
    "phase" text,
    "submission_deadline" date not null,
    "voting_deadlind" date not null
);


alter table "public"."session" enable row level security;

create table "public"."submission" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "session_id" bigint,
    "user_id" bigint,
    "track_id" text not null
);


alter table "public"."submission" enable row level security;

create table "public"."vote" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "session_id" bigint,
    "voter_id" bigint,
    "submission_id" bigint,
    "points" numeric not null
);


alter table "public"."vote" enable row level security;

CREATE UNIQUE INDEX club_membership_pkey ON public.club_membership USING btree (id);

CREATE UNIQUE INDEX club_pkey ON public.club USING btree (id);

CREATE UNIQUE INDEX gauntlet_pkey ON public.gauntlet USING btree (id);

CREATE UNIQUE INDEX profile_email_key ON public.profile USING btree (email);

CREATE UNIQUE INDEX profile_pkey ON public.profile USING btree (id);

CREATE UNIQUE INDEX profile_username_key ON public.profile USING btree (username);

CREATE UNIQUE INDEX session_pkey ON public.session USING btree (id);

CREATE UNIQUE INDEX submission_pkey ON public.submission USING btree (id);

CREATE UNIQUE INDEX vote_pkey ON public.vote USING btree (id);

alter table "public"."club" add constraint "club_pkey" PRIMARY KEY using index "club_pkey";

alter table "public"."club_membership" add constraint "club_membership_pkey" PRIMARY KEY using index "club_membership_pkey";

alter table "public"."gauntlet" add constraint "gauntlet_pkey" PRIMARY KEY using index "gauntlet_pkey";

alter table "public"."profile" add constraint "profile_pkey" PRIMARY KEY using index "profile_pkey";

alter table "public"."session" add constraint "session_pkey" PRIMARY KEY using index "session_pkey";

alter table "public"."submission" add constraint "submission_pkey" PRIMARY KEY using index "submission_pkey";

alter table "public"."vote" add constraint "vote_pkey" PRIMARY KEY using index "vote_pkey";

alter table "public"."club" add constraint "club_owner_id_fkey" FOREIGN KEY (owner_id) REFERENCES profile(id) not valid;

alter table "public"."club" validate constraint "club_owner_id_fkey";

alter table "public"."club_membership" add constraint "club_membership_club_id_fkey" FOREIGN KEY (club_id) REFERENCES club(id) not valid;

alter table "public"."club_membership" validate constraint "club_membership_club_id_fkey";

alter table "public"."club_membership" add constraint "club_membership_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profile(id) not valid;

alter table "public"."club_membership" validate constraint "club_membership_user_id_fkey";

alter table "public"."gauntlet" add constraint "gauntlet_club_id_fkey" FOREIGN KEY (club_id) REFERENCES club(id) not valid;

alter table "public"."gauntlet" validate constraint "gauntlet_club_id_fkey";

alter table "public"."profile" add constraint "profile_email_key" UNIQUE using index "profile_email_key";

alter table "public"."profile" add constraint "profile_username_key" UNIQUE using index "profile_username_key";

alter table "public"."session" add constraint "session_gauntlet_id_fkey" FOREIGN KEY (gauntlet_id) REFERENCES gauntlet(id) not valid;

alter table "public"."session" validate constraint "session_gauntlet_id_fkey";

alter table "public"."submission" add constraint "submission_session_id_fkey" FOREIGN KEY (session_id) REFERENCES session(id) not valid;

alter table "public"."submission" validate constraint "submission_session_id_fkey";

alter table "public"."submission" add constraint "submission_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profile(id) not valid;

alter table "public"."submission" validate constraint "submission_user_id_fkey";

alter table "public"."vote" add constraint "vote_session_id_fkey" FOREIGN KEY (session_id) REFERENCES session(id) not valid;

alter table "public"."vote" validate constraint "vote_session_id_fkey";

alter table "public"."vote" add constraint "vote_submission_id_fkey" FOREIGN KEY (submission_id) REFERENCES submission(id) not valid;

alter table "public"."vote" validate constraint "vote_submission_id_fkey";

alter table "public"."vote" add constraint "vote_voter_id_fkey" FOREIGN KEY (voter_id) REFERENCES profile(id) not valid;

alter table "public"."vote" validate constraint "vote_voter_id_fkey";

grant delete on table "public"."club" to "anon";

grant insert on table "public"."club" to "anon";

grant references on table "public"."club" to "anon";

grant select on table "public"."club" to "anon";

grant trigger on table "public"."club" to "anon";

grant truncate on table "public"."club" to "anon";

grant update on table "public"."club" to "anon";

grant delete on table "public"."club" to "authenticated";

grant insert on table "public"."club" to "authenticated";

grant references on table "public"."club" to "authenticated";

grant select on table "public"."club" to "authenticated";

grant trigger on table "public"."club" to "authenticated";

grant truncate on table "public"."club" to "authenticated";

grant update on table "public"."club" to "authenticated";

grant delete on table "public"."club" to "service_role";

grant insert on table "public"."club" to "service_role";

grant references on table "public"."club" to "service_role";

grant select on table "public"."club" to "service_role";

grant trigger on table "public"."club" to "service_role";

grant truncate on table "public"."club" to "service_role";

grant update on table "public"."club" to "service_role";

grant delete on table "public"."club_membership" to "anon";

grant insert on table "public"."club_membership" to "anon";

grant references on table "public"."club_membership" to "anon";

grant select on table "public"."club_membership" to "anon";

grant trigger on table "public"."club_membership" to "anon";

grant truncate on table "public"."club_membership" to "anon";

grant update on table "public"."club_membership" to "anon";

grant delete on table "public"."club_membership" to "authenticated";

grant insert on table "public"."club_membership" to "authenticated";

grant references on table "public"."club_membership" to "authenticated";

grant select on table "public"."club_membership" to "authenticated";

grant trigger on table "public"."club_membership" to "authenticated";

grant truncate on table "public"."club_membership" to "authenticated";

grant update on table "public"."club_membership" to "authenticated";

grant delete on table "public"."club_membership" to "service_role";

grant insert on table "public"."club_membership" to "service_role";

grant references on table "public"."club_membership" to "service_role";

grant select on table "public"."club_membership" to "service_role";

grant trigger on table "public"."club_membership" to "service_role";

grant truncate on table "public"."club_membership" to "service_role";

grant update on table "public"."club_membership" to "service_role";

grant delete on table "public"."gauntlet" to "anon";

grant insert on table "public"."gauntlet" to "anon";

grant references on table "public"."gauntlet" to "anon";

grant select on table "public"."gauntlet" to "anon";

grant trigger on table "public"."gauntlet" to "anon";

grant truncate on table "public"."gauntlet" to "anon";

grant update on table "public"."gauntlet" to "anon";

grant delete on table "public"."gauntlet" to "authenticated";

grant insert on table "public"."gauntlet" to "authenticated";

grant references on table "public"."gauntlet" to "authenticated";

grant select on table "public"."gauntlet" to "authenticated";

grant trigger on table "public"."gauntlet" to "authenticated";

grant truncate on table "public"."gauntlet" to "authenticated";

grant update on table "public"."gauntlet" to "authenticated";

grant delete on table "public"."gauntlet" to "service_role";

grant insert on table "public"."gauntlet" to "service_role";

grant references on table "public"."gauntlet" to "service_role";

grant select on table "public"."gauntlet" to "service_role";

grant trigger on table "public"."gauntlet" to "service_role";

grant truncate on table "public"."gauntlet" to "service_role";

grant update on table "public"."gauntlet" to "service_role";

grant delete on table "public"."profile" to "anon";

grant insert on table "public"."profile" to "anon";

grant references on table "public"."profile" to "anon";

grant select on table "public"."profile" to "anon";

grant trigger on table "public"."profile" to "anon";

grant truncate on table "public"."profile" to "anon";

grant update on table "public"."profile" to "anon";

grant delete on table "public"."profile" to "authenticated";

grant insert on table "public"."profile" to "authenticated";

grant references on table "public"."profile" to "authenticated";

grant select on table "public"."profile" to "authenticated";

grant trigger on table "public"."profile" to "authenticated";

grant truncate on table "public"."profile" to "authenticated";

grant update on table "public"."profile" to "authenticated";

grant delete on table "public"."profile" to "service_role";

grant insert on table "public"."profile" to "service_role";

grant references on table "public"."profile" to "service_role";

grant select on table "public"."profile" to "service_role";

grant trigger on table "public"."profile" to "service_role";

grant truncate on table "public"."profile" to "service_role";

grant update on table "public"."profile" to "service_role";

grant delete on table "public"."session" to "anon";

grant insert on table "public"."session" to "anon";

grant references on table "public"."session" to "anon";

grant select on table "public"."session" to "anon";

grant trigger on table "public"."session" to "anon";

grant truncate on table "public"."session" to "anon";

grant update on table "public"."session" to "anon";

grant delete on table "public"."session" to "authenticated";

grant insert on table "public"."session" to "authenticated";

grant references on table "public"."session" to "authenticated";

grant select on table "public"."session" to "authenticated";

grant trigger on table "public"."session" to "authenticated";

grant truncate on table "public"."session" to "authenticated";

grant update on table "public"."session" to "authenticated";

grant delete on table "public"."session" to "service_role";

grant insert on table "public"."session" to "service_role";

grant references on table "public"."session" to "service_role";

grant select on table "public"."session" to "service_role";

grant trigger on table "public"."session" to "service_role";

grant truncate on table "public"."session" to "service_role";

grant update on table "public"."session" to "service_role";

grant delete on table "public"."submission" to "anon";

grant insert on table "public"."submission" to "anon";

grant references on table "public"."submission" to "anon";

grant select on table "public"."submission" to "anon";

grant trigger on table "public"."submission" to "anon";

grant truncate on table "public"."submission" to "anon";

grant update on table "public"."submission" to "anon";

grant delete on table "public"."submission" to "authenticated";

grant insert on table "public"."submission" to "authenticated";

grant references on table "public"."submission" to "authenticated";

grant select on table "public"."submission" to "authenticated";

grant trigger on table "public"."submission" to "authenticated";

grant truncate on table "public"."submission" to "authenticated";

grant update on table "public"."submission" to "authenticated";

grant delete on table "public"."submission" to "service_role";

grant insert on table "public"."submission" to "service_role";

grant references on table "public"."submission" to "service_role";

grant select on table "public"."submission" to "service_role";

grant trigger on table "public"."submission" to "service_role";

grant truncate on table "public"."submission" to "service_role";

grant update on table "public"."submission" to "service_role";

grant delete on table "public"."vote" to "anon";

grant insert on table "public"."vote" to "anon";

grant references on table "public"."vote" to "anon";

grant select on table "public"."vote" to "anon";

grant trigger on table "public"."vote" to "anon";

grant truncate on table "public"."vote" to "anon";

grant update on table "public"."vote" to "anon";

grant delete on table "public"."vote" to "authenticated";

grant insert on table "public"."vote" to "authenticated";

grant references on table "public"."vote" to "authenticated";

grant select on table "public"."vote" to "authenticated";

grant trigger on table "public"."vote" to "authenticated";

grant truncate on table "public"."vote" to "authenticated";

grant update on table "public"."vote" to "authenticated";

grant delete on table "public"."vote" to "service_role";

grant insert on table "public"."vote" to "service_role";

grant references on table "public"."vote" to "service_role";

grant select on table "public"."vote" to "service_role";

grant trigger on table "public"."vote" to "service_role";

grant truncate on table "public"."vote" to "service_role";

grant update on table "public"."vote" to "service_role";

create policy "Enable read access for all users"
on "public"."profile"
as permissive
for select
to public
using (true);



